#pragma once
#ifndef THREAD_MSG_H_
#define THREAD_MSG_H_

//进程消息
#define TMSG_REQ_TIME WM_USER+1
#define TMSG_REQ_NAME WM_USER+2
#define TMSG_REQ_LIST WM_USER+3
#define TMSG_REQ_SEND_MSG WM_USER+4
#define TMSG_REQ_STATUS WM_USER+5
#define TMSG_DISCONNECT WM_USER+6

#define TMSG_RECV_TIME WM_USER+7
#define TMSG_RECV_NAME WM_USER+8
#define TMSG_RECV_LIST WM_USER+9
#define TMSG_RECV_MSG WM_USER+10
#define TMSG_MSG_FEEDBACK WM_USER+11
#define TMSG_SEND_FAIL WM_USER+12
#define TMSG_RECV_FAIL WM_USER+13
#define TMSG_RECV_CLOSE WM_USER+14
#define TMSG_REQ_TIME100 WM_USER+15

#endif // !THREAD_MSG_H_